version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:v1.15.4
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
