services:
  kafka:
    extends:
      file: ./kafka/docker-compose.yml
      service: kafka


  kafka-ui:
    extends:
      file: ./kafka/docker-compose.yml
      service: kafka-ui

  qdrant:
    extends:
      file: ./qdrant/docker-compose.yml
      service: qdrant

  ollama:
    extends:
      file: ./ollama/docker-compose.yml
      service: ollama

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    extends:
      file: ./metrics/docker-compose.yml
      service: grafana
