services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    command: ["serve"]  # просто запускаем API
    environment:
      - OLLAMA_KEEP_ALIVE=24h
