app:
  name: embedding-service
  http:
    port: 8083
  pipeline:
#    mode: reliability # performance | reliability - not valid now, for next versions
    source_batch_size: 300 # how many items load from source
    storage_batch_size: 400 # how many items save in batch in storage
    embedder_workers_cnt: 10 # how many embedder workers can work simultaneously
    source_response_timeout: 2s
    storage_response_timeout: 2s
    embedder_response_timeout: 2s #response time in seconds
    skip_embedder_errors: true # false/true - if we can only log errors and skip without interrupt all pipeline
  logging:
    level: info
  monitoring:
    enabled: true
    port: 9090
  retry_policy:
    max_retries: 3
    backoff: 2s

source:
  type: kafka
  config:
    brokers: ["localhost:9092"]
    topic: production1
    group_id: embedding-service
    offset: earliest

storage:
  type: qdrant
  config:
    url: "http://localhost:6333"
    host: "localhost"
    port: 6334
    collectionName: "test3"
    vector_size: 768
    distance: cosine
    fields:
      title: string
      year: string
      genres: string
      rating: float

embedder:
  type: ollama
  config:
    endpoint: "http://localhost:11434/api/embeddings"
    model: "nomic-embed-text"
    api_key: "YOUR_API_KEY"

#  ollama pull nomic-embed-text