source:
  type: kafka
  config:
    brokers: ["localhost:9092"]
    topic: raw-data
    group_id: embedding-service
    workers: 1 #should be equal to partitions??

storage:
  type: qdrant
  config:
    url: "http://localhost:6333"
    host: "localhost"
    port: 6334
    collectionName: "movies"
    vector_size: 768
    distance: cosine
    fields:
      title: string
      year: int
      genre: string
      rating: float

embedder:
  type: ollama
  config:
    emdpoint: "http://127.0.0.1:7878/v1/embedding"
    model: "nomic-embed-text"
    api_key: "YOUR_API_KEY"
    max_response_timeout: 10s #response time in seconds
    workers: 5
